Add controllers
ValyGer/java-shareit pull request #1
Opened 2024-02-27 21:24 UTC by ValyGer

Добавлена новая функциональность для вещей и пользователей.

2024-02-28 20:03 UTC, andrew-larkin requested changes
Привет! Отличный старт, по структуре все хорошо. Я написал комменты не повторяясь, но они актуальны для всех контроллеров, сервисов и мапперов, так что не спеши.

2024-02-28 20:03 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
в dto нельзя использовать объекты модели. Нужно использовать либо их dto, либо id

2024-02-28 20:03 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
для моделей лучше не использовать @Data, т.к. она некорректно рассчитывает хэш. Можно использовать @Getter, @Setter и т.д.

2024-02-28 20:03 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private long id;
в dto лучше не использовать примитивы, т.к. мы можем нарваться на NPE. лучше использовать врапперы (long -> Long)

2024-02-28 20:03 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
для этого приложения давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Все методы маппинга будут писаться в одну строчку благодаря ней, и нам это очень облегчит работу над этим приложением в ближайших спринтах

2024-02-28 20:03 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @PostMapping // Создание новой вещи
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(itemDto, userId)); 
Для всех методов во всех контроллерах стоит его добавить

2024-02-28 20:03 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private User requestor;
заменить на dto

2024-02-29 19:09 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
Поправил для BookingDto вместо item - id, для ItemRequestDto вместо user - id.

2024-02-29 19:09 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Откорректировал во всех классах.

2024-02-29 19:21 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private long id;
Поправил в классах dto все примитивы на классы-обертки

2024-02-29 19:21 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private User requestor;
Откорректировал

2024-02-29 21:23 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @PostMapping // Создание новой вещи
Откорректировал класс UserController и ItemController

2024-03-02 20:24 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Добавил библиотеку mapStruct. Откорректировал контроллеры для сущностей User и Item и мамер для них.

2024-03-10 10:29 UTC, merged