Add item requests
ValyGer/java-shareit pull request #8
Opened 2024-06-06 18:14 UTC by ValyGer

Добавление нового функционала: запросы вещей.
Добавление тестирования.

2024-06-07 15:25 UTC, andrew-larkin requested changes
Привет! Отличная реализация, покрытие тестам и сами тесты выполнены очень качественно. Оставил комменты по коду - местами нужно внести правки.

2024-06-07 15:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>          Item item = itemMapper.toItem(itemDto);
работу мапперов из контроллеров лучше перенести в сервисы. контроллеры должны отвечать только за маршрутизацию запросов

2024-06-07 15:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long request; // если вещь создана по запросу, то тут будет ссылка на запрос
нет, тут нужен ItemRequest с прописанными связями с другими таблицами

2024-06-07 15:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      @Column(name = "status")
в строке 30 должен быть User

2024-06-07 15:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> + * TODO Sprint add-item-requests.
после реализации TODO можно удалять

2024-06-08 05:47 UTC, ValyGer commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> + * TODO Sprint add-item-requests.
Поправил во всех файлах где было

2024-06-09 23:50 UTC, merged